-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Ensure the transactions table exists
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id TEXT NOT NULL,
    receiver_id TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_type TEXT NOT NULL,
    status TEXT DEFAULT 'SUCCESS',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the transfer_funds RPC function
DROP FUNCTION IF EXISTS public.transfer_funds(text, text, numeric, text);
DROP FUNCTION IF EXISTS public.transfer_funds(uuid, uuid, numeric, text);
DROP FUNCTION IF EXISTS public.transfer_funds;

CREATE OR REPLACE FUNCTION public.transfer_funds(
    sender TEXT,
    receiver TEXT,
    amount NUMERIC,
    payment_method TEXT
) RETURNS TEXT AS $$
DECLARE
    sender_balance NUMERIC;
    actual_receiver_id TEXT;
BEGIN
    -- Check if sender exists and get balance
    SELECT balance INTO sender_balance FROM public.customers WHERE customer_id = sender FOR UPDATE;
    IF NOT FOUND THEN
        RETURN 'SENDER_NOT_FOUND';
    END IF;

    -- Check if receiver exists by customer_id OR account_number
    SELECT customer_id INTO actual_receiver_id FROM public.customers 
    WHERE customer_id = receiver OR account_number = receiver
    LIMIT 1;

    IF actual_receiver_id IS NULL THEN
        RETURN 'RECEIVER_NOT_FOUND';
    END IF;

    -- Check sufficient funds
    IF sender_balance < amount THEN
        RETURN 'INSUFFICIENT_FUNDS';
    END IF;

    -- Deduct from sender
    UPDATE public.customers
    SET balance = balance - amount
    WHERE customer_id = sender;

    -- Add to receiver
    UPDATE public.customers
    SET balance = balance + amount
    WHERE customer_id = actual_receiver_id;

    -- Log transaction using actual_receiver_id
    INSERT INTO public.transactions (sender_id, receiver_id, amount, payment_type, status)
    VALUES (sender, actual_receiver_id, amount, payment_method, 'SUCCESS');

    -- Insert into customer_transactions if needed (for dashboard view compatibility)
    -- Just in case CustomerDashboard relies on a separate table instead of a view:
    -- INSERT INTO public.customer_transactions (customer_id, type, amount, recipient_name, created_at)
    -- VALUES (sender, 'debit', amount, receiver, NOW());
    -- INSERT INTO public.customer_transactions (customer_id, type, amount, recipient_name, created_at)
    -- VALUES (receiver, 'credit', amount, sender, NOW());

    RETURN 'SUCCESS';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS bank_name TEXT DEFAULT 'FinSecure Bank';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS ifsc_code TEXT DEFAULT 'FSEC0001234';

-- 4. Biometric Authentication Fields (WebAuthn)
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS biometric_credential_id TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS biometric_public_key TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS biometric_counter INTEGER DEFAULT 0;
